image: python:3.8

pipelines:
  default:
    - step:
        name: Build and Test Django
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python manage.py test

    - step:
        name: Build and Test React
        image: node:12.19.0
        caches:
          - node
        script:
          - cd react
          - rm -rf package-lock.json
          - rm -rf node_modules
          - npm install
          - npm run build

#    - step:
#        name: Build and Test Cypress E2E
#        caches:
#          - node
#        image: node:12.19.0
#        script:
#          - cd react
#          - npm ci
#          - npm run start:ci &
#          - npm run e2e
#        artifacts:
#          - cypress/screenshots/**
#          - cypress/videos/**
#
#definitions:
#  caches:
#    npm: $HOME/.npm
#    cypress: $HOME/.cache/Cypress
